In [2]:
# 50 Numpy functions
import numpy as np
# 1
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# 2
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
# 3
c= np.arange(24).reshape(2,3,4)
c


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
# 4
# Multidimension
d = np.array([[1,3],[4,5]])
d


array([[1, 3],
       [4, 5]])

In [6]:
# 5
# Minimum Dimension
e = np.array([0,1,2,3,4,5,6], ndmin=3)
e

array([[[0, 1, 2, 3, 4, 5, 6]]])

In [7]:
# 6
# Data type Perameters
f = np.array([1,2,3,4,5,6,7,8,9,10], dtype = complex)
f

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [8]:
# 7
g = np.array([(1,2,3),(4,5,6)])
g.ndim

2

In [10]:
# 8
# Itemsize
h = np.array((1,2,3))
h.itemsize



4

In [12]:
# 9
# D-type
h.dtype


dtype('int32')

In [13]:
# 10
# Size
h.size 


3

In [16]:
# 11
# Shape
c.shape


(2, 3, 4)

In [21]:
# 12
# Silicing
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a[0:,2])

[3 7]


In [23]:
# 13
# Boolean Function
boolean_array = np.array([1, .5, 0, 'aa', ''], dtype = bool)
print(boolean_array)

[ True  True False  True False]


In [35]:
# 14
# Multidimension
i= np.array([(1,4),(3,5),(6,8)])
i[0:2,1]

array([4, 5])

In [12]:
# 15
# Linearly Spacing
a = np.linspace(1,2,5)
print(a)


[1.   1.25 1.5  1.75 2.  ]


In [14]:
# 16
# Minimum Values
a = np.array([50,45,57])
a.min()


45

In [15]:
# 17
# Maximum Values
a.max()


57

In [18]:
# 18
# Values Sum
a = np.array([110,150,255])
a.sum()


515

In [19]:
# 19
# Square Root
np.sqrt(a)


array([10.48808848, 12.24744871, 15.96871942])

In [20]:
# 20
# Matrix Subtraction
x= np.array([(2,3,4),(1,2,3)])
y = np.array([(5,6,7),(4,5,6)])
x-y


array([[-3, -3, -3],
       [-3, -3, -3]])

In [21]:
# 21
# Matrix Addation
x+y


array([[ 7,  9, 11],
       [ 5,  7,  9]])

In [22]:
# Matrix Multiplication
x*y

array([[10, 18, 28],
       [ 4, 10, 18]])

In [23]:
# 22
# Matrix Division
x/y


array([[0.4       , 0.5       , 0.57142857],
       [0.25      , 0.4       , 0.5       ]])

In [24]:
# 23
# Vertical Stack
np.vstack((x,y))


array([[2, 3, 4],
       [1, 2, 3],
       [5, 6, 7],
       [4, 5, 6]])

In [25]:
# 24
# Horizontal Stack
np.hstack((x,y))


array([[2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6]])

In [26]:
# 25
# Contiguous Flattened Array
x.ravel()


array([2, 3, 4, 1, 2, 3])

In [27]:
# 26
# Odd Number 
arr = np.array([0,1,3,5,7,9,10,12,14,10,13,14,17,19,20])
arr[arr % 2 == 1 ]


array([ 1,  3,  5,  7,  9, 13, 17, 19])

In [28]:
# 27
# Even number
arr[arr % 2 == 0 ]


array([ 0, 10, 12, 14, 10, 14, 20])

In [30]:
# 28
# Zero Array
arrayid = np.zeros(5)
arrayid


array([0., 0., 0., 0., 0.])

In [31]:
# 29
# 2Dimensional Zero Matrix
c = np.zeros((2,3))
c


array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# 30
# Logspace Array
A = np.logspace(4,5,num=15,base= 1000.0, dtype=float)
A


array([1.00000000e+12, 1.63789371e+12, 2.68269580e+12, 4.39397056e+12,
       7.19685673e+12, 1.17876863e+13, 1.93069773e+13, 3.16227766e+13,
       5.17947468e+13, 8.48342898e+13, 1.38949549e+14, 2.27584593e+14,
       3.72759372e+14, 6.10540230e+14, 1.00000000e+15])

In [48]:
# 31
# Random Number Generator
np.random.rand(4,2)

array([[0.20998116, 0.38185163],
       [0.23738559, 0.97038834],
       [0.89491233, 0.68705123],
       [0.25261482, 0.83845296]])

In [60]:
# 32
# Random Number Generator with a range
np.random.randint(2, size= 4)

array([0, 0, 1, 0])

In [64]:
# 33
np.random.randint(15, size= (2,2))


array([[9, 2],
       [9, 8]])

In [65]:
# 34
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
# Digonal Matrix
np.diag(np.arange(1,5,5))

array([[1]])

In [71]:
# 35
# Numpy Indexing
f = np.array([1,2,3,4,5,6])
f[[1,4]]


array([2, 5])

In [73]:
# 36
# Last Value
f[5]


6

In [74]:
# 37
# Matrix Joining
Arr1= np.array([[1,2,3],[5,6,7]])
Arr2 = np.array([[2,3,4],[2,4,1]])
Arr1+Arr2

array([[ 3,  5,  7],
       [ 7, 10,  8]])

In [75]:
# 38
# Matrix Stacking Horizontal
np.hstack((Arr1,Arr2))


array([[1, 2, 3, 2, 3, 4],
       [5, 6, 7, 2, 4, 1]])

In [76]:
# Matrix Stacking Vertical
np.vstack((Arr1,Arr2))


array([[1, 2, 3],
       [5, 6, 7],
       [2, 3, 4],
       [2, 4, 1]])

In [77]:
# 39
# Concatination
np.concatenate((Arr1, Arr2))


array([[1, 2, 3],
       [5, 6, 7],
       [2, 3, 4],
       [2, 4, 1]])

In [81]:
# 40
# Append Value
np.append(Arr1,Arr2, axis = 1)


array([[1, 2, 3, 2, 3, 4],
       [5, 6, 7, 2, 4, 1]])

In [87]:
# 41
# Trignomatry function Sine
np.sin(Arr1)


array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [89]:
# 42
# Trignomatry function Cosine
np.cos(Arr1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 0.28366219,  0.96017029,  0.75390225]])

In [90]:
# 43
# Trignomatry function Tangent
np.tan(Arr1)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-3.38051501, -0.29100619,  0.87144798]])

In [91]:
# 44
# Logarithm function 
np.log(Arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015]])

In [92]:
# 45
# Exponential Function
np.exp(Arr1)


array([[   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [93]:
# 46
# Square root
np.sqrt(Arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [95]:
# 47
# Square Function
np.square(Arr1)


array([[ 1,  4,  9],
       [25, 36, 49]], dtype=int32)

In [102]:
# 48
# Circumference of circle
r=5
circumference=2*3.14*r
circumference


31.400000000000002

In [100]:
# 49
# Area of Sphere
area=4*3.14*r*r
area


314.0

In [103]:
# 50
# Area of circle
area=3.14*r*r
area


78.5